export const MOCK_OWNER = {
  id: 'owner-1',
  name: 'Carlos Mendes',
  email: 'carlos@demo.com',
  role: 'owner' as const,
  phone: '(19) 99999-0001',
  city: 'Campinas',
  state: 'SP',
  onboarding_completed: true,
  created_at: '2024-01-15T10:00:00Z',
}

export const MOCK_COMPANY = {
  id: 'company-1',
  name: 'Ana Rodrigues',
  email: 'ana@solartech.com.br',
  role: 'company' as const,
  company_name: 'SolarTech Instalações',
  cnpj: '12.345.678/0001-90',
  website: 'https://solartech.com.br',
  description: 'Empresa especializada em instalação de painéis fotovoltaicos com 8 anos de experiência.',
  onboarding_completed: true,
  created_at: '2024-01-10T10:00:00Z',
}

export const MOCK_SPACES = [
  {
    id: 'space-1',
    owner_id: 'owner-1',
    type: 'terreno',
    address: 'Rodovia D. Pedro I, km 132',
    city: 'Campinas',
    state: 'SP',
    area_m2: 2500,
    solar_orientation: ['norte', 'leste'],
    roof_type: null,
    desired_rent: 3200,
    status: 'available',
    description: 'Terreno plano com excelente incidência solar. Acesso fácil por rodovia. Ideal para usina fotovoltaica de médio porte.',
    lat: -22.9068,
    lng: -47.0626,
    created_at: '2024-02-01T10:00:00Z',
    space_photos: [],
  },
  {
    id: 'space-2',
    owner_id: 'owner-1',
    type: 'telhado',
    address: 'Av. Paulista, 1200 — Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    area_m2: 850,
    solar_orientation: ['norte'],
    roof_type: 'laje',
    desired_rent: 1800,
    status: 'negotiating',
    description: 'Telhado comercial com estrutura reforçada. Fácil acesso por escada interna. Ótima visibilidade e exposição solar.',
    lat: -23.5613,
    lng: -46.6565,
    created_at: '2024-02-10T10:00:00Z',
    space_photos: [],
  },
  {
    id: 'space-3',
    owner_id: 'owner-demo',
    type: 'terreno',
    address: 'Rua das Acácias, 400',
    city: 'Belo Horizonte',
    state: 'MG',
    area_m2: 1200,
    solar_orientation: ['norte', 'oeste'],
    roof_type: null,
    desired_rent: 1500,
    status: 'available',
    description: 'Terreno em área industrial com infraestrutura elétrica disponível. Documentação regularizada.',
    lat: -19.9167,
    lng: -43.9345,
    created_at: '2024-02-15T10:00:00Z',
    space_photos: [],
  },
  {
    id: 'space-4',
    owner_id: 'owner-demo',
    type: 'telhado',
    address: 'Rua dos Pinheiros, 800',
    city: 'Curitiba',
    state: 'PR',
    area_m2: 600,
    solar_orientation: ['norte', 'leste'],
    roof_type: 'metalica',
    desired_rent: 900,
    status: 'available',
    description: 'Telhado industrial com estrutura metálica robusta. Alta incidência solar durante todo o ano.',
    lat: -25.4284,
    lng: -49.2733,
    created_at: '2024-03-01T10:00:00Z',
    space_photos: [],
  },
  {
    id: 'space-5',
    owner_id: 'owner-demo',
    type: 'terreno',
    address: 'Estrada da Produção, km 8',
    city: 'Ribeirão Preto',
    state: 'SP',
    area_m2: 5000,
    solar_orientation: ['norte'],
    roof_type: null,
    desired_rent: 6000,
    status: 'available',
    description: 'Grande terreno rural com excelente exposição solar. Ideal para fazenda solar de grande porte. Área plana.',
    lat: -21.1784,
    lng: -47.8108,
    created_at: '2024-03-05T10:00:00Z',
    space_photos: [],
  },
  {
    id: 'space-6',
    owner_id: 'owner-demo',
    type: 'telhado',
    address: 'Av. Beira Mar, 320',
    city: 'Fortaleza',
    state: 'CE',
    area_m2: 450,
    solar_orientation: ['norte', 'leste', 'oeste'],
    roof_type: 'ceramica',
    desired_rent: 750,
    status: 'available',
    description: 'Telhado residencial em área nobre com exposição solar privilegiada. Excelente para sistema de energia distribuída.',
    lat: -3.7327,
    lng: -38.5270,
    created_at: '2024-03-10T10:00:00Z',
    space_photos: [],
  },
]

export const MOCK_INTERESTS = [
  {
    id: 'interest-1',
    space_id: 'space-1',
    company_id: 'company-1',
    status: 'accepted',
    created_at: '2024-03-01T10:00:00Z',
    space: MOCK_SPACES[0],
    company_name: 'SolarTech Instalações',
  },
  {
    id: 'interest-2',
    space_id: 'space-3',
    company_id: 'company-1',
    status: 'pending',
    created_at: '2024-03-10T10:00:00Z',
    space: MOCK_SPACES[2],
    company_name: 'SolarTech Instalações',
  },
  {
    id: 'interest-3',
    space_id: 'space-4',
    company_id: 'company-demo',
    status: 'pending',
    created_at: '2024-03-12T10:00:00Z',
    space: MOCK_SPACES[3],
    company_name: 'Energia Verde Ltda',
  },
]

export const MOCK_MESSAGES = [
  {
    id: 'msg-1',
    interest_id: 'interest-1',
    sender_id: 'company-1',
    content: 'Olá Carlos! Vi seu terreno em Campinas e fiquei muito interessado. Temos um projeto de 200kWp que se encaixa perfeitamente na área disponível.',
    created_at: '2024-03-02T09:00:00Z',
    read_at: '2024-03-02T09:15:00Z',
  },
  {
    id: 'msg-2',
    interest_id: 'interest-1',
    sender_id: 'owner-1',
    content: 'Boa tarde, Ana! Que ótimo. O terreno está disponível desde o início do ano. Quais seriam as condições do contrato?',
    created_at: '2024-03-02T14:30:00Z',
    read_at: '2024-03-02T15:00:00Z',
  },
  {
    id: 'msg-3',
    interest_id: 'interest-1',
    sender_id: 'company-1',
    content: 'Propomos um contrato de 20 anos com pagamento mensal de R$ 3.200, reajuste anual pelo IPCA e toda a manutenção por nossa conta. Podemos agendar uma visita técnica essa semana?',
    created_at: '2024-03-03T10:00:00Z',
    read_at: null,
  },
]
